"""user model

Revision ID: 007808b5f9fe
Revises: 
Create Date: 2023-03-14 16:48:35.614929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007808b5f9fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('user_phone', sa.String(length=13), nullable=True),
    sa.Column('user_pw', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
