"""empty message

Revision ID: 822d173e8d4d
Revises: d9dcb35fd8a9
Create Date: 2023-03-19 14:19:19.864339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822d173e8d4d'
down_revision = 'd9dcb35fd8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('scenario_idx', sa.Integer(), nullable=False),
    sa.Column('scenario_title', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_idx'], ['scenario.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('item',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('scenario_idx', sa.Integer(), nullable=False),
    sa.Column('scenario_title', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_idx'], ['scenario.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('country_element',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('scenario_title', sa.String(length=100), nullable=False),
    sa.Column('country_idx', sa.Integer(), nullable=True),
    sa.Column('country_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_idx'], ['country.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('item_element',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('scenario_title', sa.String(length=100), nullable=False),
    sa.Column('item_idx', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_idx'], ['item.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('items_characters',
    sa.Column('item_idx', sa.Integer(), nullable=False),
    sa.Column('character_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_idx'], ['character.idx'], ),
    sa.ForeignKeyConstraint(['item_idx'], ['item.idx'], ),
    sa.PrimaryKeyConstraint('item_idx', 'character_idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_characters')
    op.drop_table('item_element')
    op.drop_table('country_element')
    op.drop_table('item')
    op.drop_table('country')
    # ### end Alembic commands ###
