"""empty message

Revision ID: 97dd487d124a
Revises: ffdd68a417af
Create Date: 2023-03-17 08:56:54.154105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97dd487d124a'
down_revision = 'ffdd68a417af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('scenario_idx', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_idx'], ['scenario.idx'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('element',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('character_idx', sa.String(length=50), nullable=True),
    sa.Column('element', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_idx'], ['character.idx'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_idx', sa.Integer(), nullable=True))
        batch_op.drop_constraint('scenario_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_idx'], ['idx'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scenario_ibfk_1', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('user_idx')

    op.drop_table('element')
    op.drop_table('character')
    # ### end Alembic commands ###
