"""empty message

Revision ID: ae828ef0655a
Revises: b0b1269a932b
Create Date: 2023-03-18 22:50:42.392407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae828ef0655a'
down_revision = 'b0b1269a932b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_element',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('scenario_title', sa.String(length=100), nullable=False),
    sa.Column('character_idx', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.String(length=50), nullable=False),
    sa.Column('element', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['character_idx'], ['character.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.drop_table('element')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    op.create_table('element',
    sa.Column('idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('character_idx', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('character_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('element', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_opened', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_idx'], ['character.idx'], name='element_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('character_element')
    # ### end Alembic commands ###
