"""empty message

Revision ID: fbe0336f02ad
Revises: ae828ef0655a
Create Date: 2023-03-19 09:10:26.116968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbe0336f02ad'
down_revision = 'ae828ef0655a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('element')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
